name: yupiwatch
description: modern and open source video player
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  chewie: ^1.7.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  media_kit: ^1.1.10+1
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.4
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.1
  win32: ^5.1.1
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Optional: Add custom fonts
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: fonts/SFProDisplay-Regular.ttf
  #       - asset: fonts/SFProDisplay-Medium.ttf
  #         weight: 500
  #       - asset: fonts/SFProDisplay-Semibold.ttf
  #         weight: 600
  #       - asset: fonts/SFProDisplay-Bold.ttf
  #         weight: 700

# Platform specific configurations
flutter_intl:
  enabled: false